### ISSUE TITLE
CCID With Certs site and Discourse

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#14]
Coming back to deal with CCID. I am not sure if I did it, but the plugin seems deleted from https://certificates.creativecommons.org/

Before returning, to clarify what we hope to have- let users have authoring accounts on https://certificates.creativecommons.org/quests so their work there is associated with a user. 

Questions- when CCID is implemented...

* Trying to figure out account creation flow. How are new WP accounts created? Is that manual? Is it a matter of creating a username that is their email used to create CCID? Or can anyone with a CCID account create their own account on the site?
* Same for Discourse. If someone has a CCID account, can they automatically create a discourse account as a member? 

thanks

**Comment by rheaplex** [comment]
WordPress: it depends how the site is configured. We can either have everyone sign up through CCID. Or we can have only editors sign up through CCID then use JetPack commenting if we want people to be able to comment with their social media accounts rather than going to the trouble of signing up for a CCID. The only slight wrinkle is that people have to log in to WordPress using CCID before we can grant them edit permission.

Discourse: yes anyone can register for a CCID then sign in to create an account. I think approval is currently on but we could turn it off then deal with the spammers as they arrive. ;-)

**Comment by cogdog** [comment]
**Wordpress:** There's an extra wrinkle maybe in being multisite, right now we have no permissions for creating accounts. To allow self-creation of accounts, we might need something like https://wordpress.org/plugins/join-my-multisite/ to allow it one only one site.

In the quest bank they actually do not need any editing or even authoring capabilities. All their writing is done via a front page form, not the WP dashboard. I just need a way to know who they are, to attach a user ID to the things they contribute, so even a contributor or subscriber level is ok. Non participant commenting is not a need.

So having them first make CCID seems like a good route. This gets them into discourse. What happens when they get to Wordpress? It can be done so it expects a CCID login, and if not we send them there?

**Discourse:** This works. Let's deal with spam later.
